package app.privateaudio

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.util.Locale

class Layer41LocalizationContractTest {
    @Test
    fun standardAndroidLocaleConfigurationUsesEnglishDefaultResources() {
        assertTrue(appBuildSource.contains("generateLocaleConfig = true"))
        assertEquals("unqualifiedResLocale=en-US", resourcesProperties.trim())
        assertTrue(defaultStrings.contains("name=\"settings_system_default\">Default</string>"))
        assertFalse(defaultStrings.contains("translatable=\"false\""))
        localeDirectories.forEach { localeDirectory ->
            val localeStrings = File(localeDirectory, "strings.xml").readText()
            assertEquals(localeDirectory.name, stringKeys(defaultStrings), stringKeys(localeStrings))
            assertEquals(localeDirectory.name, placeholders(defaultStrings), placeholders(localeStrings))
        }
        assertEquals("Melayu", nativeLocaleName("ms"))
        assertTrue(malayStrings.contains("name=\"routing_notification_text\">Menunggu audio dialihkan</string>"))
        assertTrue(malayStrings.contains("name=\"settings_language_android_13_required\"") && malayStrings.contains("bahasa sistem"))
        assertTrue(malayStrings.contains("name=\"settings_proximity_screen\">Matikan skrin berhampiran telinga anda</string>"))
        assertTrue(malayStrings.contains("name=\"settings_about_body\">Private Audio membantu mengalihkan audio suara yang disokong ke alat dengar terbina dalam telefon anda.</string>"))
        assertTrue(malayStrings.contains("hidupkan, kembangkan dan tutup"))
        assertEquals("Italiano", nativeLocaleName("it"))
        assertTrue(italianStrings.contains("name=\"routing_notification_text\">In attesa di reindirizzare l\\'audio</string>"))
        assertTrue(italianStrings.contains("name=\"settings_language_android_13_required\"") && italianStrings.contains("lingua di sistema"))
        assertTrue(italianStrings.contains("name=\"settings_language_body\"") && italianStrings.contains("lingua del dispositivo"))
        assertTrue(italianStrings.contains("name=\"settings_proximity_screen\">Spegni lo schermo vicino all\\'orecchio</string>"))
        assertTrue(italianStrings.contains("altoparlante auricolare integrato"))
        assertTrue(italianStrings.contains("attivare, espandere e chiudere"))
        assertEquals("Română", nativeLocaleName("ro"))
        assertTrue(romanianStrings.contains("name=\"routing_notification_text\">Se așteaptă redirecționarea sunetului</string>"))
        assertTrue(romanianStrings.contains("name=\"settings_language_android_13_required\"") && romanianStrings.contains("limba sistemului"))
        assertTrue(romanianStrings.contains("name=\"settings_language_body\"") && romanianStrings.contains("limba dispozitivului"))
        assertTrue(romanianStrings.contains("name=\"settings_proximity_screen\">Oprește ecranul lângă ureche</string>"))
        assertTrue(romanianStrings.contains("casca încorporată a telefonului"))
        assertTrue(romanianStrings.contains("activare, extindere și închidere"))
        assertEquals("Svenska", nativeLocaleName("sv"))
        assertTrue(swedishStrings.contains("name=\"routing_notification_text\">Väntar på att växla ljud</string>"))
        assertTrue(swedishStrings.contains("name=\"settings_language_android_13_required\"") && swedishStrings.contains("systemspråket"))
        assertTrue(swedishStrings.contains("name=\"settings_language_body\"") && swedishStrings.contains("enhetens språk"))
        assertTrue(swedishStrings.contains("name=\"settings_proximity_screen\">Stäng av skärmen nära örat</string>"))
        assertTrue(swedishStrings.contains("telefonens inbyggda samtalslur"))
        assertTrue(swedishStrings.contains("slå på, expandera och stänga"))
        assertTrue(swedishStrings.contains("name=\"state_ready\">Redo</string>"))
        assertTrue(swedishStrings.contains("name=\"state_waiting\">Väntar</string>"))
        assertTrue(swedishStrings.contains("name=\"state_active\">Aktiv</string>"))
        assertTrue(swedishStrings.contains("name=\"state_error\">Fel</string>"))
        assertEquals("Norsk bokmål", nativeLocaleName("nb"))
        assertTrue(norwegianBokmalStrings.contains("name=\"routing_notification_text\">Venter på å bytte lyd</string>"))
        assertTrue(norwegianBokmalStrings.contains("name=\"settings_language_android_13_required\"") && norwegianBokmalStrings.contains("systemspråket"))
        assertTrue(norwegianBokmalStrings.contains("name=\"settings_language_body\"") && norwegianBokmalStrings.contains("språket på enheten"))
        assertTrue(norwegianBokmalStrings.contains("name=\"settings_proximity_screen\">Slå av skjermen nær øret</string>"))
        assertTrue(norwegianBokmalStrings.contains("telefonens innebygde ørehøyttaler"))
        assertTrue(norwegianBokmalStrings.contains("slå på, utvide og lukke"))
        assertTrue(norwegianBokmalStrings.contains("name=\"state_ready\">Klar</string>"))
        assertTrue(norwegianBokmalStrings.contains("name=\"state_waiting\">Venter</string>"))
        assertTrue(norwegianBokmalStrings.contains("name=\"state_active\">Aktiv</string>"))
        assertTrue(norwegianBokmalStrings.contains("name=\"state_error\">Feil</string>"))
        assertEquals("Dansk", nativeLocaleName("da"))
        assertTrue(danishStrings.contains("name=\"routing_notification_text\">Venter på at skifte lyd</string>"))
        assertTrue(danishStrings.contains("name=\"settings_language_android_13_required\"") && danishStrings.contains("systemsproget"))
        assertTrue(danishStrings.contains("name=\"settings_language_body\"") && danishStrings.contains("enhedens sprog"))
        assertTrue(danishStrings.contains("name=\"settings_proximity_screen\">Sluk skærmen tæt på øret</string>"))
        assertTrue(danishStrings.contains("telefonens indbyggede ørestykke"))
        assertTrue(danishStrings.contains("tænde, udvide og lukke"))
        assertTrue(danishStrings.contains("name=\"state_ready\">Klar</string>"))
        assertTrue(danishStrings.contains("name=\"state_waiting\">Venter</string>"))
        assertTrue(danishStrings.contains("name=\"state_active\">Aktiv</string>"))
        assertTrue(danishStrings.contains("name=\"state_error\">Fejl</string>"))
        assertEquals("Íslenska", nativeLocaleName("is"))
        assertTrue(icelandicStrings.contains("name=\"routing_notification_text\">Bíður eftir að skipta um hljóðúttak</string>"))
        assertTrue(icelandicStrings.contains("name=\"settings_language_android_13_required\"") && icelandicStrings.contains("tungumáli kerfisins"))
        assertTrue(icelandicStrings.contains("name=\"settings_language_body\"") && icelandicStrings.contains("tungumáli tækisins"))
        assertTrue(icelandicStrings.contains("name=\"settings_proximity_screen\">Slökkva á skjánum nálægt eyranu</string>"))
        assertTrue(icelandicStrings.contains("innbyggða símahátalarann"))
        assertTrue(icelandicStrings.contains("kveikja, stækka og loka"))
        assertTrue(icelandicStrings.contains("name=\"state_ready\">Tilbúið</string>"))
        assertTrue(icelandicStrings.contains("name=\"state_waiting\">Bíður</string>"))
        assertTrue(icelandicStrings.contains("name=\"state_active\">Virkt</string>"))
        assertTrue(icelandicStrings.contains("name=\"state_error\">Villa</string>"))
        assertEquals("Føroyskt", nativeLocaleName("fo"))
        assertTrue(faroeseStrings.contains("name=\"routing_notification_text\">Bíðar eftir at skifta ljóðið</string>"))
        assertTrue(faroeseStrings.contains("name=\"settings_language_android_13_required\"") && faroeseStrings.contains("skipanarmálinum"))
        assertTrue(faroeseStrings.contains("name=\"settings_language_body\"") && faroeseStrings.contains("málinum á tólinum"))
        assertTrue(faroeseStrings.contains("name=\"settings_proximity_screen\">Sløkk skíggjan nær oyranum</string>"))
        assertTrue(faroeseStrings.contains("innbygda hátalaran ovast á telefonini, sum verður brúktur við oyrað undir telefonsamrøðum"))
        assertTrue(faroeseStrings.contains("tendra, víðka og lata aftur"))
        assertTrue(faroeseStrings.contains("name=\"state_ready\">Klárt</string>"))
        assertTrue(faroeseStrings.contains("name=\"state_waiting\">Bíðar</string>"))
        assertTrue(faroeseStrings.contains("name=\"state_active\">Virkið</string>"))
        assertTrue(faroeseStrings.contains("name=\"state_error\">Villa</string>"))
        assertEquals("ಕನ್ನಡ", nativeLocaleName("kn"))
        assertTrue(kannadaStrings.contains("name=\"routing_notification_text\">ಆಡಿಯೊ ಸ್ವಿಚ್ ಆಗಲು ಕಾಯುತ್ತಿದೆ</string>"))
        assertTrue(kannadaStrings.contains("name=\"settings_language_android_13_required\"") && kannadaStrings.contains("ಸಿಸ್ಟಮ್ ಭಾಷೆ"))
        assertTrue(kannadaStrings.contains("name=\"settings_proximity_screen\">ಕಿವಿಯ ಬಳಿ ಸ್ಕ್ರೀನ್ ಆಫ್ ಮಾಡಿ</string>"))
        assertTrue(kannadaStrings.contains("name=\"settings_about_body\">Private Audio ಆಡಿಯೊವನ್ನು ಫೋನ್‌ನ ಇಯರ್‌ಪೀಸ್‌ಗೆ ಸ್ವಿಚ್ ಮಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.</string>"))
        assertTrue(kannadaStrings.contains("ಆನ್ ಮಾಡಲು, ವಿಸ್ತರಿಸಲು ಮತ್ತು ಮುಚ್ಚಲು"))
        assertTrue(kannadaStrings.filterNot { it.isWhitespace() }.any { it in '\u0C80'..'\u0CFF' })
        assertEquals("ગુજરાતી", nativeLocaleName("gu"))
        assertTrue(gujaratiStrings.contains("name=\"routing_notification_text\">ઑડિયો સ્વિચ થવાની રાહ જોઈ રહ્યું છે</string>"))
        assertTrue(gujaratiStrings.contains("name=\"state_waiting\">રાહ જોઈ રહ્યું છે</string>"))
        assertTrue(gujaratiStrings.contains("name=\"state_active\">સક્રિય</string>"))
        assertTrue(gujaratiStrings.contains("name=\"settings_language_android_13_required\"") && gujaratiStrings.contains("સિસ્ટમ ભાષા"))
        assertTrue(gujaratiStrings.contains("name=\"settings_proximity_screen\">કાન પાસે સ્ક્રીન બંધ કરો</string>"))
        assertTrue(gujaratiStrings.contains("name=\"settings_about_body\">Private Audio ઑડિયોને ફોનના ઇયરપીસ પર સ્વિચ કરવામાં મદદ કરે છે.</string>"))
        assertEquals("मराठी", nativeLocaleName("mr"))
        assertTrue(marathiStrings.contains("name=\"routing_notification_text\">ऑडिओ स्विच होण्याची प्रतीक्षा करत आहे</string>"))
        assertTrue(marathiStrings.contains("name=\"state_waiting\">प्रतीक्षा</string>"))
        assertTrue(marathiStrings.contains("name=\"state_active\">सक्रिय</string>"))
        assertTrue(marathiStrings.contains("name=\"settings_language_android_13_required\"") && marathiStrings.contains("सिस्टीम भाषा"))
        assertTrue(marathiStrings.contains("name=\"settings_proximity_screen\">कानाजवळ स्क्रीन बंद करा</string>"))
        assertTrue(marathiStrings.contains("name=\"settings_about_body\">Private Audio ऑडिओ फोनच्या इयरपीसवर स्विच करण्यात मदत करते.</string>"))
        assertEquals("తెలుగు", nativeLocaleName("te"))
        assertTrue(teluguStrings.contains("name=\"routing_notification_text\">ఆడియోను మార్చడానికి వేచి ఉంది</string>"))
        assertTrue(teluguStrings.contains("name=\"state_waiting\">వేచి ఉంది</string>"))
        assertTrue(teluguStrings.contains("name=\"state_active\">యాక్టివ్</string>"))
        assertTrue(teluguStrings.contains("name=\"settings_language_android_13_required\"") && teluguStrings.contains("సిస్టమ్ భాష"))
        assertTrue(teluguStrings.contains("name=\"settings_proximity_screen\">చెవి దగ్గర స్క్రీన్‌ను ఆఫ్ చేయండి</string>"))
        assertTrue(teluguStrings.contains("name=\"settings_about_body\">Private Audio ఆడియోను ఫోన్ ఇయర్‌పీస్‌కు మార్చడంలో సహాయపడుతుంది.</string>"))
        assertEquals("தமிழ்", nativeLocaleName("ta"))
        assertTrue(tamilStrings.contains("name=\"routing_notification_text\">ஆடியோவை மாற்றக் காத்திருக்கிறது</string>"))
        assertTrue(tamilStrings.contains("name=\"state_waiting\">காத்திருக்கிறது</string>"))
        assertTrue(tamilStrings.contains("name=\"state_active\">செயலில் உள்ளது</string>"))
        assertTrue(tamilStrings.contains("name=\"settings_proximity_screen\">காதுக்கு அருகில் திரையை அணை</string>"))
        assertTrue(tamilStrings.contains("name=\"settings_about_body\">தொலைபேசியின் இயர்பீஸுக்கு ஆடியோவை மாற்ற Private Audio உதவுகிறது.</string>"))
        assertEquals("ไทย", nativeLocaleName("th"))
        assertTrue(thaiStrings.contains("name=\"routing_notification_text\">กำลังรอสลับเสียง</string>"))
        assertTrue(thaiStrings.contains("name=\"product_subtitle\">คุยกับ AI แบบเป็นส่วนตัว เหมือนคุยโทรศัพท์</string>"))
        assertTrue(thaiStrings.contains("name=\"state_ready\">พร้อม</string>"))
        assertTrue(thaiStrings.contains("name=\"state_waiting\">กำลังรอ</string>"))
        assertTrue(thaiStrings.contains("name=\"state_active\">กำลังใช้งาน</string>"))
        assertTrue(thaiStrings.contains("name=\"state_error\">ข้อผิดพลาด</string>"))
        assertTrue(thaiStrings.contains("name=\"settings\">การตั้งค่า</string>"))
        assertTrue(thaiStrings.contains("name=\"settings_system_default\">ค่าเริ่มต้น</string>"))
        assertTrue(thaiStrings.contains("name=\"settings_about_body\">Private Audio ช่วยสลับเสียงไปยังหูฟังด้านบนของโทรศัพท์</string>"))
        assertEquals("日本語", nativeLocaleName("ja"))
        assertTrue(japaneseStrings.contains("name=\"routing_notification_text\">音声の切り替えを待機中</string>"))
        assertTrue(japaneseStrings.contains("name=\"state_ready\">準備完了</string>"))
        assertTrue(japaneseStrings.contains("name=\"state_waiting\">待機中</string>"))
        assertTrue(japaneseStrings.contains("name=\"state_active\">使用中</string>"))
        assertTrue(japaneseStrings.contains("name=\"state_error\">エラー</string>"))
        assertEquals("Kiswahili", nativeLocaleName("sw"))
        assertTrue(swahiliStrings.contains("name=\"routing_notification_text\">Inasubiri kuelekeza sauti</string>"))
        assertTrue(swahiliStrings.contains("name=\"state_ready\">Tayari</string>"))
        assertTrue(swahiliStrings.contains("name=\"state_waiting\">Inasubiri</string>"))
        assertTrue(swahiliStrings.contains("name=\"state_active\">Imewashwa</string>"))
        assertTrue(swahiliStrings.contains("name=\"state_error\">Hitilafu</string>"))
        assertEquals("Naijíriá Píjin", nativeLocaleName("pcm"))
        assertTrue(nigerianPidginStrings.contains("name=\"routing_notification_text\">Dey wait to route audio</string>"))
        assertTrue(nigerianPidginStrings.contains("name=\"state_ready\">Ready</string>"))
        assertTrue(nigerianPidginStrings.contains("name=\"state_waiting\">Dey wait</string>"))
        assertTrue(nigerianPidginStrings.contains("name=\"state_active\">Active</string>"))
        assertTrue(nigerianPidginStrings.contains("name=\"state_error\">Error</string>"))
        assertEquals("اردو", nativeLocaleName("ur"))
        assertTrue(urduStrings.contains("name=\"routing_notification_text\">آڈیو منتقل ہونے کا انتظار ہے</string>"))
        assertTrue(urduStrings.contains("name=\"state_ready\">تیار</string>"))
        assertTrue(urduStrings.contains("name=\"state_waiting\">انتظار میں</string>"))
        assertTrue(urduStrings.contains("name=\"state_active\">فعال</string>"))
        assertTrue(urduStrings.contains("name=\"state_error\">خرابی</string>"))
        assertEquals("فارسی", nativeLocaleName("fa"))
        assertTrue(persianStrings.contains("name=\"routing_notification_text\">در انتظار هدایت صدا</string>"))
        assertTrue(persianStrings.contains("name=\"product_subtitle\">مثل تماس تلفنی، خصوصی با هوش مصنوعی صحبت کنید.</string>"))
        assertTrue(persianStrings.contains("name=\"state_ready\">آماده</string>"))
        assertTrue(persianStrings.contains("name=\"state_waiting\">در انتظار</string>"))
        assertTrue(persianStrings.contains("name=\"state_active\">فعال</string>"))
        assertTrue(persianStrings.contains("name=\"state_error\">خطا</string>"))
        assertTrue(persianStrings.contains("name=\"power_control\">روشن کردن</string>"))
        assertTrue(persianStrings.contains("گزارش عیب‌یابی"))
        assertFalse(persianStrings.contains('ي'))
        assertFalse(persianStrings.contains('ك'))
        assertEquals("Tiếng Việt", nativeLocaleName("vi"))
        assertTrue(vietnameseStrings.contains("name=\"routing_notification_text\">Đang chờ chuyển đổi âm thanh</string>"))
        assertTrue(vietnameseStrings.contains("name=\"product_subtitle\">Trò chuyện riêng tư với AI, như một cuộc gọi điện thoại.</string>"))
        assertTrue(vietnameseStrings.contains("name=\"state_ready\">Sẵn sàng</string>"))
        assertTrue(vietnameseStrings.contains("name=\"state_waiting\">Đang chờ</string>"))
        assertTrue(vietnameseStrings.contains("name=\"state_active\">Đang hoạt động</string>"))
        assertTrue(vietnameseStrings.contains("name=\"state_error\">Lỗi</string>"))
        assertTrue(vietnameseStrings.contains("name=\"settings\">Cài đặt</string>"))
        assertTrue(vietnameseStrings.contains("name=\"settings_system_default\">Mặc định</string>"))
        assertTrue(vietnameseStrings.contains("name=\"settings_about_body\">Private Audio giúp chuyển âm thanh sang loa trong của điện thoại.</string>"))
        assertEquals("Bahasa Indonesia", nativeLocaleName("id"))
        assertTrue(indonesianStrings.contains("name=\"routing_notification_text\">Menunggu pengalihan audio</string>"))
        assertTrue(indonesianStrings.contains("name=\"state_ready\">Siap</string>"))
        assertTrue(indonesianStrings.contains("name=\"state_waiting\">Menunggu</string>"))
        assertTrue(indonesianStrings.contains("name=\"state_active\">Aktif</string>"))
        assertTrue(indonesianStrings.contains("name=\"state_error\">Error</string>"))
        assertEquals("العربية", nativeLocaleName("ar"))
        assertTrue(arabicStrings.contains("name=\"routing_notification_text\">في انتظار توجيه الصوت</string>"))
        assertTrue(arabicStrings.contains("name=\"state_ready\">جاهز</string>"))
        assertTrue(arabicStrings.contains("name=\"state_waiting\">في الانتظار</string>"))
        assertTrue(arabicStrings.contains("name=\"state_active\">نشط</string>"))
        assertTrue(arabicStrings.contains("name=\"state_error\">خطأ</string>"))
        assertEquals("हिन्दी", nativeLocaleName("hi"))
        assertTrue(hindiStrings.contains("name=\"routing_notification_text\">ऑडियो भेजे जाने का इंतज़ार है</string>"))
        assertTrue(hindiStrings.contains("name=\"state_ready\">तैयार</string>"))
        assertTrue(hindiStrings.contains("name=\"state_waiting\">इंतज़ार में</string>"))
        assertTrue(hindiStrings.contains("name=\"state_active\">चालू</string>"))
        assertTrue(hindiStrings.contains("name=\"state_error\">गड़बड़ी</string>"))
        assertTrue(simplifiedChineseStrings.contains("name=\"routing_notification_text\">正在等待音频重定向</string>"))
        assertTrue(simplifiedChineseStrings.contains("name=\"state_ready\">就绪</string>"))
        assertTrue(simplifiedChineseStrings.contains("name=\"state_waiting\">等待中</string>"))
        assertTrue(simplifiedChineseStrings.contains("name=\"state_active\">已启用</string>"))
        assertTrue(simplifiedChineseStrings.contains("name=\"state_error\">错误</string>"))
        assertTrue(traditionalChineseStrings.contains("name=\"routing_notification_text\">正在等待重新導向音訊</string>"))
        assertTrue(traditionalChineseStrings.contains("name=\"state_ready\">就緒</string>"))
        assertTrue(traditionalChineseStrings.contains("name=\"state_waiting\">等待中</string>"))
        assertTrue(traditionalChineseStrings.contains("name=\"state_active\">已啟用</string>"))
        assertTrue(traditionalChineseStrings.contains("name=\"state_error\">錯誤</string>"))
        assertEquals("Português (Brasil)", nativeLocaleName("pt-BR"))
        assertEquals("Português (Portugal)", nativeLocaleName("pt-PT"))
        assertTrue(brazilianPortugueseStrings.contains("name=\"state_waiting\">Aguardando</string>"))
        assertTrue(brazilianPortugueseStrings.contains("name=\"settings\">Configurações</string>"))
        assertTrue(brazilianPortugueseStrings.contains("alto-falante de chamadas do telefone"))
        assertTrue(europeanPortugueseStrings.contains("name=\"state_waiting\">A aguardar</string>"))
        assertTrue(europeanPortugueseStrings.contains("name=\"settings\">Definições</string>"))
        assertTrue(europeanPortugueseStrings.contains("auricular integrado do telemóvel"))
        val spanishLocale = Locale.forLanguageTag("es")
        val spanishNativeName = spanishLocale.getDisplayName(spanishLocale).replaceFirstChar { first ->
            if (first.isLowerCase()) first.titlecase(spanishLocale) else first.toString()
        }
        assertEquals("Español", spanishNativeName)
        assertTrue(spanishStrings.contains("name=\"state_ready\">Listo</string>"))
        assertTrue(spanishStrings.contains("name=\"state_waiting\">Esperando</string>"))
        assertTrue(spanishStrings.contains("name=\"state_active\">Activo</string>"))
        assertTrue(spanishStrings.contains("name=\"state_error\">Error</string>"))
        val frenchLocale = Locale.forLanguageTag("fr")
        val frenchNativeName = frenchLocale.getDisplayName(frenchLocale).replaceFirstChar { first ->
            if (first.isLowerCase()) first.titlecase(frenchLocale) else first.toString()
        }
        assertEquals("Français", frenchNativeName)
        assertTrue(frenchStrings.contains("name=\"state_ready\">Prêt</string>"))
        assertTrue(frenchStrings.contains("name=\"state_waiting\">En attente</string>"))
        assertTrue(frenchStrings.contains("name=\"state_active\">Actif</string>"))
        assertTrue(frenchStrings.contains("name=\"state_error\">Erreur</string>"))
        val russianLocale = Locale.forLanguageTag("ru")
        val russianNativeName = russianLocale.getDisplayName(russianLocale).replaceFirstChar { first ->
            if (first.isLowerCase()) first.titlecase(russianLocale) else first.toString()
        }
        assertEquals("Русский", russianNativeName)
        assertTrue(russianStrings.contains("name=\"state_ready\">Готово</string>"))
        assertTrue(russianStrings.contains("name=\"state_waiting\">Ожидание</string>"))
        assertTrue(russianStrings.contains("name=\"state_active\">Активно</string>"))
        assertTrue(russianStrings.contains("name=\"state_error\">Ошибка</string>"))
        val lithuanianLocale = Locale.forLanguageTag("lt")
        val lithuanianNativeName = lithuanianLocale.getDisplayName(lithuanianLocale).replaceFirstChar { first ->
            if (first.isLowerCase()) first.titlecase(lithuanianLocale) else first.toString()
        }
        assertEquals("Lietuvių", lithuanianNativeName)
        assertTrue(lithuanianStrings.contains("name=\"state_ready\">Paruošta</string>"))
        assertTrue(lithuanianStrings.contains("name=\"state_waiting\">Laukia</string>"))
        assertTrue(lithuanianStrings.contains("name=\"state_active\">Aktyvu</string>"))
        assertTrue(lithuanianStrings.contains("name=\"state_error\">Klaida</string>"))
        val belarusianLocale = Locale.forLanguageTag("be")
        val belarusianNativeName = belarusianLocale.getDisplayName(belarusianLocale).replaceFirstChar { first ->
            if (first.isLowerCase()) first.titlecase(belarusianLocale) else first.toString()
        }
        assertEquals("Беларуская", belarusianNativeName)
        assertTrue(belarusianStrings.contains("name=\"state_ready\">Гатова</string>"))
        assertTrue(belarusianStrings.contains("name=\"state_waiting\">Чакае</string>"))
        assertTrue(belarusianStrings.contains("name=\"state_active\">Актыўна</string>"))
        assertTrue(belarusianStrings.contains("name=\"state_error\">Памылка</string>"))
        val ukrainianLocale = Locale.forLanguageTag("uk")
        val ukrainianNativeName = ukrainianLocale.getDisplayName(ukrainianLocale).replaceFirstChar { first ->
            if (first.isLowerCase()) first.titlecase(ukrainianLocale) else first.toString()
        }
        assertEquals("Українська", ukrainianNativeName)
        assertTrue(ukrainianStrings.contains("name=\"state_ready\">Готово</string>"))
        assertTrue(ukrainianStrings.contains("name=\"state_waiting\">Очікує</string>"))
        assertTrue(ukrainianStrings.contains("name=\"state_active\">Активно</string>"))
        assertTrue(ukrainianStrings.contains("name=\"state_error\">Помилка</string>"))
    }

    @Test
    fun finnishFrozenLocalizationSemanticsRemainIntact() {
        assertEquals("Suomi", nativeLocaleName("fi"))
        assertTrue(finnishStrings.contains("name=\"routing_notification_text\">Odottaa äänen ohjaamista</string>"))
        assertTrue(finnishStrings.contains("name=\"settings_language_body\"") && finnishStrings.contains("laitteesi kieltä"))
        assertTrue(finnishStrings.contains("name=\"settings_language_android_13_required\"") && finnishStrings.contains("Tämä laite käyttää järjestelmän kieltä."))
        assertTrue(finnishStrings.contains("name=\"settings_proximity_screen\">Sammuta näyttö korvan lähellä</string>"))
        assertTrue(finnishStrings.contains("puhelimen sisäänrakennettuun kuulokkeeseen"))
        assertTrue(finnishStrings.contains("Virran kytkemisen, laajentamisen ja sulkemisen säätimet"))
        assertTrue(finnishStrings.contains("name=\"state_ready\">Valmis</string>"))
        assertTrue(finnishStrings.contains("name=\"state_waiting\">Odottaa</string>"))
        assertTrue(finnishStrings.contains("name=\"state_active\">Aktiivinen</string>"))
        assertTrue(finnishStrings.contains("name=\"state_error\">Virhe</string>"))
    }

    @Test
    fun estonianFrozenLocalizationSemanticsRemainIntact() {
        assertEquals("Eesti", nativeLocaleName("et"))
        assertTrue(estonianStrings.contains("name=\"routing_notification_text\">Ootab heli suunamist</string>"))
        assertTrue(estonianStrings.contains("name=\"settings_language_body\"") && estonianStrings.contains("seadme keelt"))
        assertTrue(estonianStrings.contains("name=\"settings_language_android_13_required\"") && estonianStrings.contains("See seade kasutab süsteemi keelt."))
        assertTrue(estonianStrings.contains("name=\"settings_proximity_screen\">Lülita ekraan kõrva lähedal välja</string>"))
        assertTrue(estonianStrings.contains("telefoni sisseehitatud kuular"))
        assertTrue(estonianStrings.contains("Sisselülitamise, laiendamise ja sulgemise juhtelemendid"))
        assertTrue(estonianStrings.contains("name=\"state_ready\">Valmis</string>"))
        assertTrue(estonianStrings.contains("name=\"state_waiting\">Ootab</string>"))
        assertTrue(estonianStrings.contains("name=\"state_active\">Aktiivne</string>"))
        assertTrue(estonianStrings.contains("name=\"state_error\">Viga</string>"))
    }

    @Test
    fun hungarianFrozenLocalizationSemanticsRemainIntact() {
        assertEquals("Magyar", nativeLocaleName("hu"))
        assertTrue(hungarianStrings.contains("name=\"routing_notification_text\">Várakozás a hang átirányítására</string>"))
        assertTrue(hungarianStrings.contains("name=\"settings_language_body\"") && hungarianStrings.contains("eszközöd nyelvét"))
        assertTrue(hungarianStrings.contains("name=\"settings_language_android_13_required\"") && hungarianStrings.contains("Ez az eszköz a rendszer nyelvét követi."))
        assertTrue(hungarianStrings.contains("name=\"settings_proximity_screen\">A képernyő kikapcsolása a fül közelében</string>"))
        assertTrue(hungarianStrings.contains("telefon beépített fülhallgatója"))
        assertTrue(hungarianStrings.contains("A bekapcsolás, a kibontás és a bezárás vezérlői"))
        assertTrue(hungarianStrings.contains("name=\"state_ready\">Kész</string>"))
        assertTrue(hungarianStrings.contains("name=\"state_waiting\">Várakozik</string>"))
        assertTrue(hungarianStrings.contains("name=\"state_active\">Aktív</string>"))
        assertTrue(hungarianStrings.contains("name=\"state_error\">Hiba</string>"))
    }

    @Test
    fun languageSelectionUsesPlatformConfigurationWithoutAParallelLocaleRegistry() {
        assertTrue(languagePreferencesSource.contains("LocaleConfig(context).supportedLocales"))
        assertTrue(languagePreferencesSource.contains("getSystemService(LocaleManager::class.java)"))
        assertTrue(languagePreferencesSource.contains("LocaleList.getEmptyLocaleList()"))
        assertTrue(languagePreferencesSource.contains("Build.VERSION_CODES.TIRAMISU"))
        assertFalse(languagePreferencesSource.contains("listOf(\"en-US\", \"pl\")"))
        assertFalse(languagePreferencesSource.contains("SharedPreferences"))
        assertTrue(settingsSource.contains("supportedLanguages.forEach"))
        assertTrue(settingsSource.contains("selectedLanguageTag == null"))
    }

    @Test
    fun existingOverlayRefreshesOnlyLocalizedPresentationOnConfigurationChange() {
        assertTrue(overlaySource.contains("override fun onConfigurationChanged"))
        assertTrue(overlaySource.contains("overlayView?.refreshLocalizedPresentation()"))
        assertTrue(overlaySource.contains("contentDescription = stateDescription(state)"))
        assertFalse(overlaySource.method("override fun onConfigurationChanged").contains("hideOverlay()"))
        assertFalse(overlaySource.method("override fun onConfigurationChanged").contains("bindControllerService()"))
    }

    @Test
    fun productSurfacesUseResourcesWhileDiagnosticsStayOutsideLocalization() {
        assertFalse(mainSource.contains("ClipboardManager"))
        assertTrue(mainSource.contains("R.string.diagnostic_report_saved"))
        assertTrue(mainSource.contains("R.string.diagnostic_report_save_failed"))
        assertFalse(productScreenSource.contains("Text(\""))
        assertFalse(settingsSource.contains("Text(\""))
        assertTrue(diagnosticScreenSource.contains("Text(\"PRIVATE AUDIO\""))
    }

    @Test
    fun protectedRoutingAndReportFormatterRemainSingleAndUnchangedInOwnership() {
        assertEquals(1, productionSources.sumOf { it.readText().occurrences("setCommunicationDevice(") })
        assertEquals(1, observerSource.occurrences("internal fun buildDiagnosticReport("))
        assertFalse(defaultStrings.contains("PRIVATE AUDIO DIAGNOSTIC REPORT"))
    }

    private fun String.occurrences(needle: String): Int = windowed(needle.length).count { it == needle }

    private fun String.method(signature: String): String =
        substring(indexOf(signature)).substringBefore("\n    }")

    private fun stringKeys(resources: String) =
        Regex("<string name=\"([^\"]+)\"").findAll(resources).map { it.groupValues[1] }.toList()

    private fun placeholders(resources: String) =
        Regex("<string name=\"([^\"]+)\">([^<]*)</string>").findAll(resources).associate {
            it.groupValues[1] to Regex("%\\d+\\$[a-z]").findAll(it.groupValues[2]).map { match -> match.value }.toList()
        }

    private fun nativeLocaleName(languageTag: String): String {
        val locale = Locale.forLanguageTag(languageTag)
        return locale.getDisplayName(locale).replaceFirstChar { first ->
            if (first.isLowerCase()) first.titlecase(locale) else first.toString()
        }
    }

    private companion object {
        val projectRoot = generateSequence(File(System.getProperty("user.dir")).absoluteFile) { it.parentFile }
            .first { File(it, "app/src/main").isDirectory }
        val appBuildSource = projectFile("app/build.gradle.kts").readText()
        val resourcesProperties = projectFile("app/src/main/res/resources.properties").readText()
        val defaultStrings = projectFile("app/src/main/res/values/strings.xml").readText()
        val malayStrings = projectFile("app/src/main/res/values-ms/strings.xml").readText()
        val italianStrings = projectFile("app/src/main/res/values-it/strings.xml").readText()
        val romanianStrings = projectFile("app/src/main/res/values-ro/strings.xml").readText()
        val swedishStrings = projectFile("app/src/main/res/values-sv/strings.xml").readText()
        val norwegianBokmalStrings = projectFile("app/src/main/res/values-nb/strings.xml").readText()
        val danishStrings = projectFile("app/src/main/res/values-da/strings.xml").readText()
        val icelandicStrings = projectFile("app/src/main/res/values-is/strings.xml").readText()
        val faroeseStrings = projectFile("app/src/main/res/values-fo/strings.xml").readText()
        val kannadaStrings = projectFile("app/src/main/res/values-kn/strings.xml").readText()
        val gujaratiStrings = projectFile("app/src/main/res/values-gu/strings.xml").readText()
        val marathiStrings = projectFile("app/src/main/res/values-mr/strings.xml").readText()
        val teluguStrings = projectFile("app/src/main/res/values-te/strings.xml").readText()
        val tamilStrings = projectFile("app/src/main/res/values-ta/strings.xml").readText()
        val thaiStrings = projectFile("app/src/main/res/values-th/strings.xml").readText()
        val ukrainianStrings = projectFile("app/src/main/res/values-uk/strings.xml").readText()
        val belarusianStrings = projectFile("app/src/main/res/values-be/strings.xml").readText()
        val lithuanianStrings = projectFile("app/src/main/res/values-lt/strings.xml").readText()
        val russianStrings = projectFile("app/src/main/res/values-ru/strings.xml").readText()
        val frenchStrings = projectFile("app/src/main/res/values-fr/strings.xml").readText()
        val spanishStrings = projectFile("app/src/main/res/values-es/strings.xml").readText()
        val brazilianPortugueseStrings = projectFile("app/src/main/res/values-pt-rBR/strings.xml").readText()
        val europeanPortugueseStrings = projectFile("app/src/main/res/values-pt-rPT/strings.xml").readText()
        val simplifiedChineseStrings = projectFile("app/src/main/res/values-b+zh+Hans/strings.xml").readText()
        val traditionalChineseStrings = projectFile("app/src/main/res/values-b+zh+Hant/strings.xml").readText()
        val hindiStrings = projectFile("app/src/main/res/values-hi/strings.xml").readText()
        val arabicStrings = projectFile("app/src/main/res/values-ar/strings.xml").readText()
        val indonesianStrings = projectFile("app/src/main/res/values-id/strings.xml").readText()
        val urduStrings = projectFile("app/src/main/res/values-ur/strings.xml").readText()
        val persianStrings = projectFile("app/src/main/res/values-fa/strings.xml").readText()
        val vietnameseStrings = projectFile("app/src/main/res/values-vi/strings.xml").readText()
        val nigerianPidginStrings = projectFile("app/src/main/res/values-pcm/strings.xml").readText()
        val japaneseStrings = projectFile("app/src/main/res/values-ja/strings.xml").readText()
        val swahiliStrings = projectFile("app/src/main/res/values-sw/strings.xml").readText()
        val finnishStrings = projectFile("app/src/main/res/values-fi/strings.xml").readText()
        val estonianStrings = projectFile("app/src/main/res/values-et/strings.xml").readText()
        val hungarianStrings = projectFile("app/src/main/res/values-hu/strings.xml").readText()
        val mainSource = projectFile("app/src/main/java/app/privateaudio/MainActivity.kt").readText()
        val productScreenSource = projectFile("app/src/main/java/app/privateaudio/ui/PrivateAudioScreen.kt").readText()
        val settingsSource = projectFile("app/src/main/java/app/privateaudio/ui/SettingsSheet.kt").readText()
        val diagnosticScreenSource = projectFile("app/src/main/java/app/privateaudio/ui/DiagnosticScreen.kt").readText()
        val languagePreferencesSource = projectFile("app/src/main/java/app/privateaudio/localization/AppLanguagePreferences.kt").readText()
        val overlaySource = projectFile("app/src/main/java/app/privateaudio/overlay/OverlayService.kt").readText()
        val observerSource = projectFile("app/src/main/java/app/privateaudio/diagnostic/AudioDiagnosticObserver.kt").readText()
        val productionSources = File(projectRoot, "app/src/main/java")
            .walkTopDown().filter { it.isFile && it.extension == "kt" }.toList()
        val localeDirectories = File(projectRoot, "app/src/main/res")
            .listFiles().orEmpty()
            .filter { it.isDirectory && it.name.startsWith("values-") && it.name != "values-night" }

        fun projectFile(relativePath: String) = File(projectRoot, relativePath)
    }
}
